name: Report a problem
description: Tell us about something that needs to be fixed
body:
  - type: textarea
    id: details
    attributes:
      label: What is the problem?
      description: Please provide details, to make it easier for the maintainers and other community members to address the issue.
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location of problem (optional)
      description: Where is the problem that needs to be fixed? (e.g. the name of the source file or the URL(s) of the webpage(s))
  - type: markdown
    attributes:
      value: >
        Thank you for taking time to tell us about a problem in this lesson!
